In [2]:
import pandas as pd
import numpy as py
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
import tensorflow as tf

In [4]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.7.0


In [5]:
mnist=tf.keras.datasets.mnist

In [6]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train,x_test=x_train/255.0,x_test/255.0

###### Building ML Model

In [9]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [10]:
pred=model(x_train[:1]).numpy()
pred

array([[-0.3292008 ,  0.11600147,  0.16972898, -0.01154004, -0.9633255 ,
         0.29580688, -0.0587599 , -0.42075533, -0.15774989, -0.20584665]],
      dtype=float32)

In [11]:
tf.nn.softmax(pred).numpy()

array([[0.07986137, 0.12464809, 0.1315283 , 0.10972234, 0.04235843,
        0.14920183, 0.10466169, 0.07287442, 0.09479751, 0.09034596]],
      dtype=float32)

###### Define a loss function for training using losses.SparseCategoricalCrossentropy, which takes a vector of logits and a True index and returns a scalar loss for each example.

In [12]:
loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [14]:
loss(y_train[:1], pred).numpy()

1.9024553

In [15]:
model.compile(optimizer="adam",loss=loss,metrics=["accuracy"])

In [16]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 1ms/step - loss: 0.2911 - accuracy: 0.9158
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1443 - accuracy: 0.9566
Epoch 3/5
1875/1875 [==============================] - 2s 944us/step - loss: 0.1093 - accuracy: 0.9668
Epoch 4/5
1875/1875 [==============================] - 2s 951us/step - loss: 0.0875 - accuracy: 0.9737
Epoch 5/5
1875/1875 [==============================] - 2s 849us/step - loss: 0.0753 - accuracy: 0.9767


In [17]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0761 - accuracy: 0.9773 - 699ms/epoch - 2ms/step


[0.07607495784759521, 0.9772999882698059]

In [18]:
prob_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [19]:
prob_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.92298780e-08, 2.76495493e-09, 9.28702775e-06, 5.35381914e-05,
        2.55118999e-11, 2.59753019e-08, 1.59227734e-13, 9.99935269e-01,
        2.77804389e-07, 1.60795491e-06],
       [7.46558015e-09, 2.95173577e-05, 9.99952674e-01, 1.42840927e-05,
        1.15050884e-14, 1.32825065e-07, 1.09771258e-06, 1.61505987e-12,
        2.22802009e-06, 3.51753484e-13],
       [3.33396855e-07, 9.99022484e-01, 1.78568647e-04, 3.12864654e-06,
        6.11595242e-05, 1.39623285e-06, 1.41704204e-05, 6.71716232e-04,
        4.60810479e-05, 8.70434974e-07],
       [9.99712288e-01, 2.78480936e-08, 1.57155358e-04, 2.44037551e-06,
        2.75750222e-06, 6.03536364e-06, 3.78795303e-05, 7.04071936e-05,
        3.17147681e-07, 1.06594680e-05],
       [2.93655139e-05, 3.25686855e-08, 8.44164242e-06, 1.78876505e-07,
        9.93241668e-01, 3.69097179e-05, 1.42587087e-05, 3.16124177e-04,
        1.78583241e-06, 6.35129539e-03]], dtype=float32)>